#numpy array and basic

In [3]:
import numpy as np

# create array in numpy not list

In [8]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print("1d: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2d : ",arr_2d)

1d:  [1 2 3 4 5 6]
2d :  [[1 2 3]
 [4 5 6]]


##List vs arry 

In [7]:

py_list = [1, 2, 3]
print("Multiplication in List : ",py_list*2)

array = np.array([1, 2, 3])
print("Mulitplication in array : " , array * 2)

Multiplication in List :  [1, 2, 3, 1, 2, 3]
Mulitplication in array :  [2 4 6]


#ones and zeros array


In [10]:
zeros = np.zeros((4,3))

ones = np.ones((4, 5))

print("Zeros : ", zeros)
print("Ones : ",ones)

Zeros :  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones :  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#constant array 

In [12]:
full = np.full((2,2),5)
print(full)

[[5 5]
 [5 5]]


#random and sqence array

In [16]:
random = np.random.random((2, 3))
print(random)

sequence = np.arange(2,12,2) #first 2 is range 3one is gap between both numbers
print(sequence)

[[0.92703429 0.84210927 0.69237435]
 [0.08052446 0.851796   0.67516218]]
[ 2  4  6  8 10]
