# Numpy array OPS

In [3]:
import numpy as np

In [5]:
arr  = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print("Basic slicing : ",arr[2:5])
print("Basic gap slicing : ",arr[2:8:2])
print("Basic : ",arr[2:8:2])




Basic slicing :  [3 4 5]
Basic gap slicing :  [3 5 7]
Basic :  [3 5 7]


In [6]:
arr2d = np.array([[1,5], [4,4], [2,2],[1,1]])
print("Sort", np.sort(arr2d, axis= 0))

Sort [[1 1]
 [1 2]
 [2 4]
 [4 5]]


# Operations in array


In [7]:
elements = arr[arr % 2 == 0]
print(elements)

[2 4 6 8]


In [8]:
mask = elements < 5
print(mask)

print(elements[mask])


[ True  True False False]
[2 4]


In [10]:
arr_3d = np.array([[[1, 2, 3, 4],[9, 7, 5, 4]],[[22, 54, 67, 87], [32, 44, 65, 76]]])

print(np.sort(arr_3d, axis=1))

[[[ 1  2  3  4]
  [ 9  7  5  4]]

 [[22 44 65 76]
  [32 54 67 87]]]


# advance ops

In [ ]:
sales_data = np.array