#numpy array and basic

In [3]:
import numpy as np

# create array in numpy not list

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print("1d: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2d : ",arr_2d)

1d:  [1 2 3 4 5 6]
2d :  [[1 2 3]
 [4 5 6]]


##List vs arry 

In [5]:

py_list = [1, 2, 3]
print("Multiplication in List : ",py_list*2)

array = np.array([1, 2, 3])
print("Mulitplication in array : " , array * 2)

Multiplication in List :  [1, 2, 3, 1, 2, 3]
Mulitplication in array :  [2 4 6]


#ones and zeros array


In [6]:
zeros = np.zeros((4,3))

ones = np.ones((4, 5))

print("Zeros : ", zeros)
print("Ones : ",ones)

Zeros :  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones :  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#constant array 

In [7]:
full = np.full((2,2),5)
print(full)

[[5 5]
 [5 5]]


#random and sqence array

In [8]:
random = np.random.random((2, 3))
print(random)

sequence = np.arange(2,12,2) #first 2 is range 3one is gap between both numbers
print(sequence)

[[0.11484758 0.8035609  0.76930536]
 [0.055532   0.89707374 0.57935025]]
[ 2  4  6  8 10]


# Vector Matrix Tensor

In [9]:

vector = np.array([1, 2, 3])
Matrix = np.array([[1,2,3],[4, 5, 6],[7, 8, 9]])
Tensor = np.array([[[1,2],[4,5]],[[6,7],[8,9]]])

print(vector)
print(Matrix)
print(Tensor.dtype) #type
print(Tensor.size) # how much elemts 
print(Tensor.ndim) #3d array


[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
8
3


reshape array


In [ ]:
arr = np.arange(9)
print("\n Defult array : ",arr)

reshaped = arr.reshape((3,3))
print("\n Reshaped 3X3 : ",reshaped )

flat = reshaped.flatten()
print("\n Flatter : ", flat)  #this copy the original and convert into flat in other SIde Ravel() flat original array

Transposed = reshaped.T #this convert 3X4 into 4X3 something like a'
print(Transposed)
